/**
 * UI chrome (section titles, field labels) per language. This is presentation,
 * not CV data, so it lives with the templates rather than in cv.yaml.
 */

module.exports = {
  en: {
    about: "Professional Summary",
    ai: "AI & Python Capabilities",
    skills: "Technical Skills",
    experience: "Professional Experience",
    projects: "Side Projects",
    education: "Education",
    languages: "Languages",
    client: "Client",
    context: "Project context",
    responsibilities: "Responsibilities",
    achievements: "Achievements & Impact",
    challenges: "Technical Challenges",
    tech: "Technical Environment",
    role: "Role",
    type: "Type",
    repository: "Repository",
    link: "Link",
    booking: "Book a meeting",
    linkedin: "LinkedIn",
    github: "GitHub",
    portfolio: "Portfolio",
  },
  fr: {
    about: "Résumé Professionnel",
    ai: "Capacités IA & Python",
    skills: "Compétences Techniques",
    experience: "Expérience Professionnelle",
    projects: "Projets Personnels",
    education: "Formation",
    languages: "Langues",
    client: "Client",
    context: "Contexte du projet",
    responsibilities: "Responsabilités",
    achievements: "Réalisations & Impact",
    challenges: "Défis Techniques",
    tech: "Environnement Technique",
    role: "Rôle",
    type: "Type",
    repository: "Dépôt",
    link: "Lien",
    booking: "Prendre rendez-vous",
    linkedin: "LinkedIn",
    github: "GitHub",
    portfolio: "Portfolio",
  },
};
